spring:
  rabbitmq:
    host: 192.168.3.133
    port: 5672
    password: guest
    username: guest
    listener:
      simple:
        prefetch: 1 #最大接收数 Qos 只适用于Direct交换机
        acknowledge-mode: manual  #简答分发的默认directExchange，否则routingProducer不生效
      direct: # 仅针对自定义的directExchange
        acknowledge-mode: manual #手动确认接收
  redis:
    port: 6379
    host: 192.168.3.100
    password: 123456
    lettuce:
      pool:
        max-active: 8        #连接池最大链接数默认值为8
        max-wait: -1        #连接池最大阻塞时间（使用负值表示没有限制）默认为-1
        max-idle: 8        #连接池中的最大空闲连接数 默认为8
        min-idle: 0         #连接池中的最小空闲连接数 默认为8