spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scaffolding?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimeZone=GMT%2B8
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: admin
    username: admin
    listener:
      simple:
        prefetch: 1 #最大接收数 Qos 只适用于Direct交换机
        acknowledge-mode: manual  #简答分发的默认directExchange，否则routingProducer不生效
      direct: # 仅针对自定义的directExchange
        acknowledge-mode: manual #手动确认接收
    virtual-host: my_vhost #docker 中设置了virtual-host
  redis:
    port: 6379
    host: 127.0.0.1
#    password: 123456
    lettuce:
      pool:
        max-active: 8        #连接池最大链接数默认值为8
        max-wait: -1        #连接池最大阻塞时间（使用负值表示没有限制）默认为-1
        max-idle: 8        #连接池中的最大空闲连接数 默认为8
        min-idle: 0         #连接池中的最小空闲连接数 默认为8



server:
  tomcat:
    accept-count: 500
    max-connections: 10000 #最大可被连接数，默认为10000
    max-threads: 1000  #最大工作线程数
    min-spare-threads: 10 #最小工作线程数
